[ci_updates] pylint + Python3 compatibility
mojin-robotics/flexbe_behavior_engine pull request #3
Opened 2020-01-30 15:36 UTC by fmessmer

@LoyVanBeek @benmaidel 
this is needed for https://github.com/mojin-robotics/mojin_flexbe/pull/46 to pass...there, it's already used in the rosinstall: https://github.com/mojin-robotics/mojin_flexbe/pull/46/commits/3e4b1e87708037170c15add71925f87b53099cc4

please review

2020-01-31 08:19 UTC, LoyVanBeek commented on flexbe_core/src/flexbe_core/behavior.py
> -            elif type(attr) is long:
<strike>
Not sure this is backwards compatible to the extend we want. 
In python2, like C++, a `long` is different from an `int`. In Py3, they're the same. </strike>

This is fine: https://www.python.org/dev/peps/pep-0237/

2020-01-31 08:23 UTC, LoyVanBeek requested changes
1 small change needed, LGTM otherwise. 
However, we should make a PR to upstream for @pschillinger to review as well quickly

2020-01-31 08:23 UTC, LoyVanBeek commented on flexbe_core/src/flexbe_core/behavior.py
> -            elif type(attr) is long:
We might actually remove this elif-blocks though

2020-01-31 09:47 UTC, fmessmer commented
there already is a PR to `team-vigir`: https://github.com/team-vigir/flexbe_behavior_engine/pull/102

2020-02-03 10:37 UTC, merged

2020-02-03 10:38 UTC, fmessmer commented
got merged to the upstream/vigir repo....so I updated our `develop` branch